name: Docker

on:
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        uses: openzim/docker-publish-action@v10
        with:
          image-name: ${{ github.repository }}
          registries: ghcr.io
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GH_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GH_TOKEN }}
          on-master: master
          latest-on-tag: true
          build-args:
            VERSION={tag}
          manual-tag: latest
